// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAExU8-tR3tzh9pNBWVBKz54GbXAwzfYJU',
    appId: '1:132565211613:web:96321f397c1f06737ebe34',
    messagingSenderId: '132565211613',
    projectId: 'testedesafio-4b3d4',
    authDomain: 'testedesafio-4b3d4.firebaseapp.com',
    storageBucket: 'testedesafio-4b3d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaHn6Vq-ucIWYwvxoRQzjmxmQhDgN5Nn4',
    appId: '1:132565211613:android:de1eefd95f724a2e7ebe34',
    messagingSenderId: '132565211613',
    projectId: 'testedesafio-4b3d4',
    storageBucket: 'testedesafio-4b3d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpSJ7P8go2BKuee7d18jTFM3XxSPFepz0',
    appId: '1:132565211613:ios:9944533fa0d402867ebe34',
    messagingSenderId: '132565211613',
    projectId: 'testedesafio-4b3d4',
    storageBucket: 'testedesafio-4b3d4.appspot.com',
    iosClientId: '132565211613-ukcg930dk7vmmfhdc9nvuii4443uraue.apps.googleusercontent.com',
    iosBundleId: 'com.example.desa111',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpSJ7P8go2BKuee7d18jTFM3XxSPFepz0',
    appId: '1:132565211613:ios:9944533fa0d402867ebe34',
    messagingSenderId: '132565211613',
    projectId: 'testedesafio-4b3d4',
    storageBucket: 'testedesafio-4b3d4.appspot.com',
    iosClientId: '132565211613-ukcg930dk7vmmfhdc9nvuii4443uraue.apps.googleusercontent.com',
    iosBundleId: 'com.example.desa111',
  );
}
